name: Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mayawalk.py'
      - 'docs/**'

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: python -m pip install Sphinx

      - name: Build Documentation
        run: sphinx-build docs/source docs/build/html

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build/html
